### ISSUE TITLE
Meeting #4

### ISSUE THREAD

**Issue by nbren12** [pangeo-data/ml-workflow-examples#9]
Hi everyone. Let's try to set up the next meeting. In the last thread, I had suggested Monday July 1 at 9AM PDT. If that works for you, please "thumbs up" this post.

**Comment by nbren12** [comment]
Ok. Let's do that time. I set up a meeting with Vulcan's zoom account. Here is the link: https://vulcan.zoom.us/j/950374623

**Comment by nbren12** [comment]
Actually, I am just a "Basic" user so it has a limit of 40 mins. Could you set it up with your google meet account @jhamman?

**Comment by TomAugspurger** [comment]
I can make a Google meet invite if needed.

**Comment by djgagne** [comment]
I discovered what caused the issue last time with Google Meet not letting in non-NCAR people without my permission. If the people are invitees on the Meet event with Google accounts, then they can access the event without any problem. Otherwise they have to ask for permission to be let in.

I am remotely attending a thesis defense that morning, and it will probably be finished by 9 AM PDT, but I don't want to commit to attending just in case it runs long. @TomAugspurger it would be better for you to set up the Google Meet this time.

**Comment by TomAugspurger** [comment]
Sent out an invite with the details. Ping me if you want to be added, or you can join on Monday at 9 AM PDT.

https://meet.google.com/rfi-nyqa-svy

**Comment by nbren12** [comment]
Thanks for setting that up Tom!

**Comment by TomAugspurger** [comment]
@nbren12 can you make & share a Dropbox Paper link for the minutes when you get a chance?

**Comment by nbren12** [comment]
Sure!

https://paper.dropbox.com/doc/Meeting-notes-ML-Working-Group--AgFLHpiIEDV1e~PN_Pofn4CuAQ-4qEhXDwJp9u1WpyGfpbrT
